module.exports={
    "paper":[
        {
            "paperIndex":"0",
                "paperName":"Principles for Strengthening the Integrity of Clinical Research",
                "paperAuthor":"David Korn, Susan Ehringhaus",
                "paperType":"Essay",
                "paperDate":"21 Apr 2006",
                "paperJournal":"PLOS ONE",
                "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
                "paperView":"16116",
                "paperCitation":"0",
                "paperDownload":"22",
                "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
                "paperIntroduction":" often referred to ",
                "paperMethodology":"Metformin (N,N-dimethylbiguanide) is often referred to as a magic drug.",
                "paperResDis":"In total, the entity-entity citation network based on Metformin information",
                "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"1",
                "paperName":"Principles for Strengthening the Integrity of Clinical Research",
                "paperAuthor":"David Korn, Susan Ehringhaus",
                "paperType":"Essay",
                "paperDate":"21 Apr 2006",
                "paperJournal":"PLOS ONE",
                "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
                "paperView":"16116",
                "paperCitation":"0",
                "paperDownload":"22",
                "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
                "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
                "paperResDis":"In total, the entity-entity citation network based on Metformin information",
                "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"2",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"3",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"4",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"5",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"6",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"7",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"8",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"9",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"10",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"11",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"12",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"13",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"14",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"15",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"16",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"17",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"18",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"19",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        },
        {   "paperIndex":"20",
            "paperName":"Principles for Strengthening the Integrity of Clinical Research",
            "paperAuthor":"David Korn, Susan Ehringhaus",
            "paperType":"Essay",
            "paperDate":"21 Apr 2006",
            "paperJournal":"PLOS ONE",
            "paperDoi":"https://doi.org/10.1371/journal.pctr.0010001",
            "paperView":"16116",
            "paperCitation":"0",
            "paperDownload":"22",
            "paperAbstract":"This paper proposes entitymetrics to measure the impact of knowledge units.",
            "paperMethodology":"Metformin (N,"+"N-dimethylbiguanide) is often referred to as a magic drug.",
            "paperResDis":"In total, the entity-entity citation network based on Metformin information",
            "paperConclusion":"This paper proposes entitymetrics to measure the impact of knowledge units at"
        }

        ],
    "length": '21'
};